### ISSUE TITLE
工具的使用方法

### ISSUE THREAD

**Issue by asdascac** [Hissec/HisSword#1]

**Comment by asdascac** [comment]
你好，请问下该工具是使用命令是什么，MD里面没有写

**Comment by Hissec** [comment]
代理模式+客户端反向回连server，eg（默认为透传端口转发+服务直连客户侧）：
server:
      HisServer_amd64.exe -a 127.0.0.1 -p 1080 -A x.x.x.x -P 8888  --reverse=true --proxy=true 
client:
      HisSword -a x.x.x.x -p 8888 --reverse=true
